Evaluated two regression and classification models
model evaluation results:

Regression Model Evaluation:
mean_squared_error:
 Support Vector Regression Score: 7645113572011320.00
 Logistic Regression Score: 10054008360486724.00

mean_absolute_error:
 Support Vector Regression Score: 87232287.47
 Logistic Regression Score: 94626386.18


Classification Model Evaluation:
accuracy_score:
 Decision Tree Classifier Score: 1.00
 Random Forest Classifier Score: 1.00

precision_score:
 Decision Tree Classifier Score: 1.00
 Random Forest Classifier Score: 1.00


Best Classification Model per Metric:
accuracy_score: Decision Tree Classifier
precision_score: Decision Tree Classifier

Best Regression Model per Metric:
mean_squared_error: Support Vector Regression
mean_absolute_error: Support Vector Regression